# Generated by Django 5.2 on 2025-06-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='notes_main',
        ),
    ]
